package hscript;

class Config {
	public static final ALLOWED_CUSTOM_CLASSES = [
		"flixel",
		"funkin.backend",
		"funkin.shaders",
		"funkin.modding.scripts",
		"funkin.options",
		"funkin.objects",
		"haxe.ds",
		"haxe.crypto",
		"haxe.io.Bytes",
		"Math",
		"Std",
		"StringTools",
		"Date",
	];
	public static final ALLOWED_ABSTRACT_AND_ENUM = [
		"funkin.backend",
		"flixel",
		"openfl",
		"haxe.xml",
		"haxe.CallStack",
		"haxe.ds",
		"haxe.crypto",
		"haxe.io.Bytes",
		"Math",
		"Std",
		"StringTools",
		"Date",
		"Array",
		"ArrayBuffer",
		"ByteArray",
		"Date",
		"Error",
		"Float32Array",
		"Float64Array",
		"Int16Array",
		"Int32Array",
		"Int8Array",
		"Map",
		"Number",
		"Object",
		"RegExp",
		"String",
		"Uint16Array",
		"Uint32Array",
		"Uint8Array",
		"Uint8ClampedArray",
		"Vector",
		"Void",
	];
	public static final DISALLOW_CUSTOM_CLASSES = [
		"flixel.FlxGame",
		"flixel.addons.ui.FlxUI9SliceSprite",
		"flixel.addons.ui.FlxUIList",
		"flixel.addons.ui.FlxUINumericStepper",
		"Type",
		"Reflect",
		"haxe.macro.Context",
		"haxe.rtti.Rtti"
	];
	public static final DISALLOW_ABSTRACT_AND_ENUM = [];
}
