name: Compile Target
description: Compile the selected Lime target.

inputs:
  target:
    description: Build target from the workflow matrix.
    required: true
  app-version:
    description: Application version to pass to Lime.
    required: true

runs:
  using: composite
  steps:
    - name: Compile (Apple IOS)
      if: inputs.target == 'ios'
      shell: bash
      run: |
        haxelib install format
        haxelib install hxp

        set +e
        haxelib remove lime
        set -e
        git clone --recursive https://github.com/openfl/lime
        haxelib dev lime lime
        lime rebuild tools
        haxelib run lime rebuild "${{ inputs.target }}"
        haxelib run lime build ios --app-version="${{ inputs.app-version }}" -D officialBuild -nosign

    - name: Compile (Android)
      if: inputs.target == 'android'
      shell: bash
      run: |
        haxelib run lime build android --app-version="${{ inputs.app-version }}" -D officialBuild -release -verbose -final

    - name: Compile (Apple TV)
      if: inputs.target == 'tvos'
      shell: bash
      run: |
        haxelib install format 3.8.0
        haxelib install hxp 1.3.1
        haxelib remove lime
        git clone --recursive https://github.com/openfl/lime
        haxelib dev lime lime
        haxelib remove hxcpp
        git clone --recursive https://github.com/HaxeFoundation/hxcpp.git
        haxelib dev hxcpp hxcpp
        haxelib run lime rebuild tvos
        haxelib run lime build "${{ inputs.target }}" --app-version="${{ inputs.app-version }}" -D officialBuild -nosign -final

    - name: Compile (Anyelse)
      if: inputs.target != 'ios' && inputs.target != 'tvos' && inputs.target != 'android' && runner.os != 'Windows'
      shell: bash
      run: |
        haxelib run lime build "${{ inputs.target }}" --app-version="${{ inputs.app-version }}" -D officialBuild -final

    - name: Compile (Anyelse Windows)
      if: inputs.target != 'ios' && inputs.target != 'tvos' && inputs.target != 'android' && runner.os == 'Windows'
      shell: powershell
      run: |
        haxelib run lime build "${{ inputs.target }}" --app-version="${{ inputs.app-version }}" -D officialBuild -final
