# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

  workflow_dispatch:
    inputs:
      nightly:
        default: false
        type: boolean
        description: "Create nightly release"

permissions:
  contents: write

jobs:
  build:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            artifact-name: linuxBuild
            export-path: export/release/linux/bin
            lib-path: ~/haxelib
            setup-file: ./setup/unix.sh

          - os: windows-latest
            target: windows
            artifact-name: windowsBuild
            export-path: export/release/windows/bin
            lib-path: C:/haxelib
            setup-file: ./setup/windows.ps1

          - os: macos-latest
            target: mac
            artifact-name: macBuild
            export-path: export/release/macos/bin
            lib-path: ~/haxelib
            setup-file: ./setup/unix.sh

          # - os: macos-latest
          #   target: ios
          #   artifact-name: iosBuild
          #   export-path: export/release/ios/
          #   lib-path: ~/haxelib
          #   setup-file: ./setup/unix.sh

          # - os: windows-latest
          #   target: android
          #   artifact-name: androidBuild
          #   export-path: export/release/android/bin/app/
          #   lib-path: C:/haxelib
          #   setup-file: ./setup/windows.ps1

          # - os: macos-15
          #   target: tvos
          #   artifact-name: tvosBuild
          #   export-path: export/release/tvos
          #   lib-path: ~/haxelib
          #   setup-file: ./setup/unix.sh

    runs-on: ${{ matrix.os }}
    env:
      DISCORD_RPC_ID: ${{ secrets.DISCORD_RPC_ID }}

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup build environment
        uses: ./.github/workflows/buildYmls/setup-build
        with:
          target: ${{ matrix.target }}
          lib-path: ${{ matrix.lib-path }}
          setup-file: ${{ matrix.setup-file }}

      - name: Compile target
        uses: ./.github/workflows/buildYmls/compile-target
        with:
          target: ${{ matrix.target }}
          app-version: 4.0.0-${{ github.run_id }}

      - name: Publish Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.export-path }}

  create-nightly-release:
    name: Nightly Release
    needs: build
    runs-on: ubuntu-latest
    if: ${{ (inputs.nightly || github.event_name == 'push') && !cancelled() }}

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Update nightly release
        uses: ./.github/workflows/buildYmls/nightly-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
