# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
            artifact-name: linuxBuild
            export-path: export/release/linux/bin
            lib-path: ~/haxelib
          - os: windows-latest
            target: windows
            artifact-name: windowsBuild
            export-path: export/release/windows/bin
            lib-path: C:/haxelib
            
          - os: macos-15
            target: mac
            artifact-name: macBuild
            export-path: export/release/macos/bin
            lib-path: ~/haxelib

    runs-on: ${{ matrix.os }}
    env:
      DISCORD_RPC_ID: ${{ secrets.DISCORD_RPC_ID }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      # Linux-specific dependencies
      - name: Install Linux dependencies
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install libvlc-dev libvlccore-dev

      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: ${{ matrix.lib-path }}
          key: ${{ runner.os }}-haxelib-${{ hashFiles('**/setup/commands.txt') }}
          restore-keys: |
            ${{ runner.os }}-haxelib-

      # Install Haxelib (Unix-like systems)
      - name: Install Haxelib (Unix)
        if: matrix.target != 'windows'
        run: |
          haxelib setup ${{ matrix.lib-path }}
          haxelib install hxcpp > /dev/null --quiet
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      # Install Haxelib (Windows)
      - name: Install Haxelib (Windows)
        if: matrix.target == 'windows'
        run: |
          haxelib setup ${{ matrix.lib-path }}
          haxelib install hxcpp > /dev/null --quiet
          powershell ./setup/windows.ps1
        shell: cmd

      # Skip SScript setup mode (Unix)
      - name: Skip SScript setup mode (Unix)
        if: matrix.target != 'windows'
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa

      # Skip SScript setup mode (Windows)
      - name: Skip SScript setup mode (Windows)
        if: matrix.target == 'windows'
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> %USERPROFILE%/settings.cocoa
        shell: cmd

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build ${{ matrix.target }} --app-version="4.0.0-${{ github.run_id}}" -D officialBuild

      - name: Publish Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.export-path }}

  create-nightly-release:
    name: Nightly Release
    needs: build
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create archives
        continue-on-error: true
        run: |
          cd artifacts
          zip -r ../linuxBuild.zip linuxBuild/
          zip -r ../windowsBuild.zip windowsBuild/
          zip -r ../macBuild.zip macBuild/

      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: "Nightly Release"
          body: |
            **PaoPao Engine** development release for commit ${{ github.sha }}. Since this is not a regular release, so you should use the engine if you want them.
          files: | # get all zip files
            windowsBuild.zip
            linuxBuild.zip
            macBuild.zip
